### ISSUE TITLE
Missing version of ROS2 supported

### ISSUE THREAD

**Issue by SMorettini** [UniversalRobots/Universal_Robots_ROS2_Tutorials#5]
I was having a problem running the tutorials. After hours of debugging I found out that the tutorial doesn't work correctly with ROS Humble, could you add the version the tutorial is designed for on the README?

In particular, I found out that in ROS Humble, `ur_control.launch.py` doesn't take as input `description_launchfile` so the UR20 is always launched and not the `my_robot_cell`.

**Comment by fmauch** [comment]
This is a fair point. Thanks for pointing that out.
